routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::resource('estudante', 'EstudanteController');
    Route::resource('cadeira', 'CadeiraController');
	Route::resource('curso', 'CursoController');
	Route::resource('grau', 'GrauController');
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);
});

resources/views/layouts/navbars/auth.blade.php
<div class="sidebar" data-color="white" data-active-color="danger">
    <div class="logo">
        <a href="{{ route('home') }}" class="simple-text logo-mini">
            <div class="logo-image-small">
                <img src="{{ asset('paper') }}/img/logo-small.png">
            </div>
        </a>
        <a href="#" class="simple-text logo-normal">
            {{ Auth::user()->name }}
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="{{ $elementActive == 'dashboard' ? 'active' : '' }}">
                <a href="{{ route('page.index', 'dashboard') }}">
                    <i class="nc-icon nc-bank"></i>
                    <p>{{ __('Painel principal') }}</p>
                </a>
            </li>

            <li class="{{  $elementActive == 'cadeira' ? 'active' : '' }}">
                <a data-toggle="collapse" aria-expanded="false" href="#cadeira">
                    <i class="nc-icon nc-book-bookmark"></i>
                    <p>
                        {{ __('Cadeira') }}
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="cadeira">
                    <ul class="nav">
                        <li class="{{ $elementSub == 'cadeira-index' ? 'active' : '' }}">
                            <a href="{{ route('cadeira.index') }}">
                                <span class="sidebar-mini-icon">{{ __('C') }}</span>
                                <span class="sidebar-normal">{{ __(' Cadeiras ') }}</span>
                            </a>
                        </li>
                        <li class="{{ $elementSub == 'cadeira-create' ? 'active' : '' }}">
                            <a href="{{ route('cadeira.create') }}">
                                <span class="sidebar-mini-icon">{{ __('NC') }}</span>
                                <span class="sidebar-normal">{{ __(' Nova Cadeira ') }}</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="{{  $elementActive == 'curso' ? 'active' : '' }}">
                <a data-toggle="collapse" aria-expanded="false" href="#curso">
                    <i class="nc-icon nc-briefcase-24"></i>
                    <p>
                        {{ __('Curso') }}
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="curso">
                    <ul class="nav">
                        <li class="{{ $elementSub == 'curso-index' ? 'active' : '' }}">
                            <a href="{{ route('curso.index') }}">
                                <span class="sidebar-mini-icon">{{ __('C') }}</span>
                                <span class="sidebar-normal">{{ __(' Cursos ') }}</span>
                            </a>
                        </li>
                        <li class="{{ $elementSub == 'curso-create' ? 'active' : '' }}">
                            <a href="{{ route('curso.create') }}">
                                <span class="sidebar-mini-icon">{{ __('NC') }}</span>
                                <span class="sidebar-normal">{{ __(' Novo curso ') }}</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="{{ $elementActive == 'estudante' ? 'active' : '' }}">
                <a data-toggle="collapse"  href="#estudante" >
                    <i class="nc-icon nc-single-02"></i>
                    <p>
                        {{ __('Estudante') }}
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="estudante">
                    <ul class="nav">
                        <li class="{{ $elementSub == 'estudante-index' ? 'active' : '' }}">
                            <a href="{{ route('estudante.index', 'user') }}">
                                <span class="sidebar-mini-icon">{{ __('E') }}</span>
                                <span class="sidebar-normal">{{ __(' Estudantes ') }}</span>
                            </a>
                        </li>

                        <li class="{{ $elementSub == 'estudante-create' ? 'active' : '' }}">
                            <a href="{{ route('estudante.create') }}">
                                <span class="sidebar-mini-icon">{{ __('NE') }}</span>
                                <span class="sidebar-normal">{{ __(' Novo estudante ') }}</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </li>

            <li class="{{ $elementActive == 'grau' ? 'active' : '' }}">
                <a data-toggle="collapse" aria-expanded="false" href="#grau">
                    <i class="nc-icon nc-money-coins"></i>
                    <p>
                            {{ __('Grau Grau académico') }}
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="grau">
                    <ul class="nav">
                        <li class="{{ $elementSub == 'grau-index' ? 'active' : '' }}">
                            <a href="{{ route('grau.index', 'user') }}">
                                <span class="sidebar-mini-icon">{{ __('E') }}</span>
                                <span class="sidebar-normal">{{ __(' Grau Grau académico ') }}</span>
                            </a>
                        </li>

                        <li class="{{ $elementSub == 'grau-create' ? 'active' : '' }}">
                            <a href="{{ route('grau.create') }}">
                                <span class="sidebar-mini-icon">{{ __('RP') }}</span>
                                <span class="sidebar-normal">{{ __(' Registar grau ') }}</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </li>

            <li class="{{ $elementActive == 'icons' ? 'active' : '' }}">
                <a href="{{ route('page.index', 'icons') }}">
                    <i class="nc-icon nc-diamond"></i>
                    <p>{{ __('Icons') }}</p>
                </a>
            </li>
            <li class="{{ $elementActive == 'map' ? 'active' : '' }}">
                <a href="{{ route('page.index', 'map') }}">
                    <i class="nc-icon nc-pin-3"></i>
                    <p>{{ __('Maps') }}</p>
                </a>
            </li>
            <li class="{{ $elementActive == 'notifications' ? 'active' : '' }}">
                <a href="{{ route('page.index', 'notifications') }}">
                    <i class="nc-icon nc-bell-55"></i>
                    <p>{{ __('Notifications') }}</p>
                </a>
            </li>
            <li class="{{ $elementActive == 'tables' ? 'active' : '' }}">
                <a href="{{ route('page.index', 'tables') }}">
                    <i class="nc-icon nc-tile-56"></i>
                    <p>{{ __('Table List') }}</p>
                </a>
            </li>
            <li class="{{ $elementActive == 'typography' ? 'active' : '' }}">
                <a href="{{ route('page.index', 'typography') }}">
                    <i class="nc-icon nc-caps-small"></i>
                    <p>{{ __('Typography') }}</p>
                </a>
            </li>

        </ul>
    </div>
</div>

resources/views/layouts/navbars/fixed-plugin-js.blade.php
<script>
    $(document).ready(function () {
       $('.datepicker').datepicker({
    weekStart:1,
    color: 'red'
    });
    });
</script>
<script>
    $(document).ready(function () {
        $sidebar = $('.sidebar');
        $sidebar_img_container = $sidebar.find('.sidebar-background');
        $full_page = $('.full-page');
        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        window_width = $(window).width();
        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();
        // if( window_width > 767 && fixed_plugin_open == 'Dashboard' ){
        //     if($('.fixed-plugin .dropdown').hasClass('show-dropdown')){
        //         $('.fixed-plugin .dropdown').addClass('show');
        //     }
        //
        // }
        $('.fixed-plugin a').click(function (event) {
            // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
            if ($(this).hasClass('switch-trigger')) {
                if (event.stopPropagation) {
                    event.stopPropagation();
                } else if (window.event) {
                    window.event.cancelBubble = true;
                }
            }
        });
        $('.fixed-plugin .active-color span').click(function () {
            $full_page_background = $('.full-page-background');
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            var new_color = $(this).data('color');
            if ($sidebar.length != 0) {
                $sidebar.attr('data-active-color', new_color);
            }
            if ($full_page.length != 0) {
                $full_page.attr('data-active-color', new_color);
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.attr('data-active-color', new_color);
            }
        });
        $('.fixed-plugin .background-color span').click(function () {
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            var new_color = $(this).data('color');
            if ($sidebar.length != 0) {
                $sidebar.attr('data-color', new_color);
            }
            if ($full_page.length != 0) {
                $full_page.attr('filter-color', new_color);
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.attr('data-color', new_color);
            }
        });
        $('.fixed-plugin .img-holder').click(function () {
            $full_page_background = $('.full-page-background');
            $(this).parent('li').siblings().removeClass('active');
            $(this).parent('li').addClass('active');
            var new_image = $(this).find("img").attr('src');
            if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                $sidebar_img_container.fadeOut('fast', function () {
                    $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                    $sidebar_img_container.fadeIn('fast');
                });
            }
            if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');
                $full_page_background.fadeOut('fast', function () {
                    $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                    $full_page_background.fadeIn('fast');
                });
            }
            if ($('.switch-sidebar-image input:checked').length == 0) {
                var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
                var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');
                $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
            }
        });
        $('.switch-sidebar-image input').on("switchChange.bootstrapSwitch", function () {
            $full_page_background = $('.full-page-background');
            $input = $(this);
            if ($input.is(':checked')) {
                if ($sidebar_img_container.length != 0) {
                    $sidebar_img_container.fadeIn('fast');
                    $sidebar.attr('data-image', '#');
                }
                if ($full_page_background.length != 0) {
                    $full_page_background.fadeIn('fast');
                    $full_page.attr('data-image', '#');
                }
                background_image = true;
            } else {
                if ($sidebar_img_container.length != 0) {
                    $sidebar.removeAttr('data-image');
                    $sidebar_img_container.fadeOut('fast');
                }
                if ($full_page_background.length != 0) {
                    $full_page.removeAttr('data-image', '#');
                    $full_page_background.fadeOut('fast');
                }
                background_image = false;
            }
        });
        $('.switch-mini input').on("switchChange.bootstrapSwitch", function () {
            $body = $('body');
            $input = $(this);
            if (paperDashboard.misc.sidebar_mini_active == true) {
                $('body').removeClass('sidebar-mini');
                paperDashboard.misc.sidebar_mini_active = false;
                $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();
            } else {
                $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');
                setTimeout(function () {
                    $('body').addClass('sidebar-mini');
                    paperDashboard.misc.sidebar_mini_active = true;
                }, 300);
            }
            // we simulate the window Resize so the charts will get updated in realtime.
            var simulateWindowResize = setInterval(function () {
                window.dispatchEvent(new Event('resize'));
            }, 180);
            // we stop the simulation of Window Resize after the animations are completed
            setTimeout(function () {
                clearInterval(simulateWindowResize);
            }, 1000);
        });
    });
</script>

resources/views/layouts/navbars/fixed-plugin.blade.php
<div class="fixed-plugin">
    <div class="dropdown show-dropdown">
        <a href="#" data-toggle="dropdown">
            <i class="fa fa-cog fa-2x"> </i>
        </a>
        <ul class="dropdown-menu">
            <li class="header-title"> Sidebar Background</li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <div class="badge-colors text-center">
                        <span class="badge filter badge-light active" data-color="white"></span>
                        <span class="badge filter badge-dark" data-color="black"></span>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="header-title"> Sidebar Active Color</li>
            <li class="adjustments-line text-center">
                <a href="javascript:void(0)" class="switch-trigger active-color">
                    <span class="badge filter badge-primary" data-color="primary"></span>
                    <span class="badge filter badge-info" data-color="info"></span>
                    <span class="badge filter badge-success" data-color="success"></span>
                    <span class="badge filter badge-warning" data-color="warning"></span>
                    <span class="badge filter badge-danger active" data-color="danger"></span>
                </a>
            </li>
        </ul>
    </div>
</div>