routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::resource('estudante', 'EstudanteController');
    Route::resource('cadeira', 'CadeiraController');
	Route::resource('curso', 'CursoController');
	Route::resource('grau', 'GrauController');
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);
});

app/Models/Grau.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Grau extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'preco_matricula', 'preco_inscricao', 'nome'
    ];
}

app/Http/Controllers/GrauController.php
<?php

namespace App\Http\Controllers;

use App\Models\Grau;
use Illuminate\Http\Request;

class GrauController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('grau.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return Grau::create($request->all());

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Grau  $grau
     * @return \Illuminate\Http\Response
     */
    public function show(Grau $grau)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Grau  $grau
     * @return \Illuminate\Http\Response
     */
    public function edit(Grau $grau)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Grau  $grau
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Grau $grau)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Grau  $grau
     * @return \Illuminate\Http\Response
     */
    public function destroy(Grau $grau)
    {
        //
    }
}

resources/views/grau/create.blade.php
@extends('layouts.app', [
'class' => '',
'elementActive' => 'grau',
'elementSub' => 'grau-create'
])
@section('header')
Preços da instituição
@endsection
@section('content')
<div class="content">
    @include('layouts.flash-messages')
    <div class="wizard-card" data-color="orange" id="wizardForm">
        <form action="{{ route('grau.store') }}" method="POST">
            @csrf
            <div class="wizard-header text-left">
                <h4 class="wizard-title">Registar grau académico</h4>
                <p class="font-italic">Esta informação será registada na base de dados da instituição.</p>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group @error('nome') has-danger @enderror">
                        <label class="control-label" for="nome">Nome do grau académico <span
                                class="text-danger">*</span></label>
                        <input type="text" required="true" id="nome"
                            class="form-control border-input @error('nome') form-control-danger @enderror"
                            placeholder="Nome do grau académico " value="{{ old('nome') }}" name="nome">
                        @error('nome')
                        <span class="invalid-feedback" style="display: block;" role="alert">
                            <strong>{{ $message}}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group @error('preco_matricula') has-danger @enderror">
                        <label class="control-label" for="preco_matricula">Preço de matricula <span
                                class="text-danger">*</span></label>
                        <input type="text" required="true" id="preco_matricula"
                            class="form-control border-input @error('preco_matricula') form-control-danger @enderror"
                            placeholder="Preço de matricula" value="{{ old('preco_matricula') }}"
                            name="preco_matricula">
                        @error('preco_matricula')
                        <span class="invalid-feedback" style="display: block;" role="alert">
                            <strong>{{ $message}}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group @error('preco_inscricao') has-danger @enderror">
                        <label class="control-label" for="preco_inscricao">Preço de inscrição
                            <span class="text-danger">*</span></label>
                        <input type="text" required="true" id="preco_inscricao"
                            class="form-control border-input @error('preco_inscricao') form-control-danger @enderror"
                            placeholder="Código do curso" value="{{ old('preco_inscricao') }}" name="preco_inscricao">
                        @error('preco_inscricao')
                        <span class="invalid-feedback" style="display: block;" role="alert">
                            <strong>{{ $message}}</strong>
                        </span>
                        @enderror
                    </div>
                </div>

            </div>

            <div class="wizard-footer">
                <div class="pull-right">

                    <button type='submit' class='btn btn-finish btn-fill btn-info btn-wd'>Registar</button>
                </div>

                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
</div>
@endsection